<?php
/** Created by Łukasz Misiura (c) 2025 | dev.lm-ads.com **/

// Already installed — block access
if (file_exists(__DIR__ . '/data/.installed')) {
    header('Location: login.php');
    exit;
}

// Auto-detect existing installation (has .env with real API key)
if (file_exists(__DIR__ . '/.env')) {
    $envContent = file_get_contents(__DIR__ . '/.env');
    if (preg_match('/UNIFI_API_KEY=(.+)/', $envContent, $m)) {
        $key = trim($m[1]);
        if ($key !== '' && $key !== 'your-api-key' && $key !== 'your-api-key-here') {
            @file_put_contents(__DIR__ . '/data/.installed', date('Y-m-d H:i:s'));
            header('Location: login.php');
            exit;
        }
    }
}

$error = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $fields = [
        'UNIFI_CONTROLLER_URL' => trim($_POST['controller_url'] ?? ''),
        'UNIFI_API_KEY'        => trim($_POST['api_key'] ?? ''),
        'UNIFI_SITE'           => trim($_POST['site'] ?? 'default'),
        'ADMIN_USERNAME'       => trim($_POST['admin_username'] ?? ''),
        'ADMIN_PASSWORD'       => $_POST['admin_password'] ?? '',
        'ADMIN_FULL_NAME'      => trim($_POST['admin_full_name'] ?? ''),
        'ADMIN_EMAIL'          => trim($_POST['admin_email'] ?? ''),
        'DEBUG'                => 'false',
    ];

    // Validate required fields
    if (empty($fields['UNIFI_CONTROLLER_URL'])) {
        $error = 'Controller URL is required';
    } elseif (empty($fields['UNIFI_API_KEY'])) {
        $error = 'API Key is required';
    } elseif (empty($fields['ADMIN_USERNAME'])) {
        $error = 'Admin username is required';
    } elseif (empty($fields['ADMIN_PASSWORD'])) {
        $error = 'Admin password is required';
    } elseif (strlen($fields['ADMIN_PASSWORD']) < 6) {
        $error = 'Password must be at least 6 characters';
    }

    if (empty($error)) {
        // Build .env content
        $env = "# MiniDash Configuration\n";
        $env .= "# Generated by Setup Wizard on " . date('Y-m-d H:i:s') . "\n\n";
        $env .= "# UniFi Controller\n";
        $env .= "UNIFI_CONTROLLER_URL={$fields['UNIFI_CONTROLLER_URL']}\n";
        $env .= "UNIFI_API_KEY={$fields['UNIFI_API_KEY']}\n";
        $env .= "UNIFI_SITE={$fields['UNIFI_SITE']}\n\n";
        $env .= "# Admin credentials\n";
        $env .= "ADMIN_USERNAME={$fields['ADMIN_USERNAME']}\n";
        $env .= "ADMIN_PASSWORD={$fields['ADMIN_PASSWORD']}\n";
        $env .= "ADMIN_FULL_NAME={$fields['ADMIN_FULL_NAME']}\n";
        $env .= "ADMIN_EMAIL={$fields['ADMIN_EMAIL']}\n\n";
        $env .= "# Debug mode\n";
        $env .= "DEBUG=false\n";

        $envPath = __DIR__ . '/.env';
        $dataDir = __DIR__ . '/data';

        // Ensure data directory exists
        if (!is_dir($dataDir)) {
            @mkdir($dataDir, 0770, true);
        }

        // Write .env
        if (@file_put_contents($envPath, $env) === false) {
            $error = 'Cannot write .env file — check directory permissions';
        } else {
            @chmod($envPath, 0600);
            // Mark as installed
            @file_put_contents($dataDir . '/.installed', date('Y-m-d H:i:s'));
            $success = true;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - MiniDash</title>
    <link rel="icon" type="image/png" href="img/favicon.png">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="assets/css/fonts.css">
    <link rel="stylesheet" href="dashboard.css">
    <script src="assets/js/lucide.min.js"></script>
    <style>
        .glass-card:hover { transform: none; }
        .setup-input {
            width: 100%;
            padding: 0.65rem 0.75rem 0.65rem 2.5rem;
            background: rgba(30, 41, 59, 0.5);
            border: 1px solid rgba(255, 255, 255, 0.05);
            border-radius: 0.75rem;
            color: #e2e8f0;
            outline: none;
            transition: all 0.2s;
        }
        .setup-input:focus {
            border-color: rgba(59, 130, 246, 0.5);
            box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.25);
        }
        .setup-input::placeholder { color: #475569; }
    </style>
</head>
<body class="min-h-screen flex items-center justify-center p-4">
    <div class="w-full max-w-lg">
        <!-- Logo/Header -->
        <div class="text-center mb-8">
            <div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-slate-800/50 mb-4 shadow-xl shadow-blue-500/10 border border-white/10">
                <img src="img/logo_lm-u.png" alt="MiniDash" class="w-10 h-10 opacity-90">
            </div>
            <h1 class="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-indigo-400">
                MiniDash
            </h1>
            <p class="text-slate-500 text-sm mt-2 font-medium tracking-wide uppercase">Initial Setup</p>
        </div>

        <?php if ($success): ?>
            <div class="glass-card p-8 shadow-2xl text-center space-y-6">
                <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-emerald-500/10 text-emerald-400">
                    <i data-lucide="check-circle" class="w-10 h-10"></i>
                </div>
                <h2 class="text-xl font-bold text-white">Setup Complete</h2>
                <p class="text-slate-400 text-sm">Configuration saved. You can now log in with your admin credentials.</p>
                <a href="login.php"
                   class="inline-flex items-center justify-center gap-2 w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3.5 rounded-xl transition shadow-xl shadow-blue-600/20">
                    <span>Go to Login</span>
                    <i data-lucide="arrow-right" class="w-4 h-4"></i>
                </a>
            </div>
        <?php else: ?>
            <div class="glass-card p-8 shadow-2xl relative overflow-hidden">
                <div class="absolute -top-24 -right-24 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl"></div>

                <?php if ($error): ?>
                    <div class="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg mb-6 flex items-center gap-3">
                        <i data-lucide="alert-circle" class="w-5 h-5 shrink-0"></i>
                        <span class="text-sm font-medium"><?= htmlspecialchars($error) ?></span>
                    </div>
                <?php endif; ?>

                <form method="POST" class="space-y-7 relative z-10">
                    <!-- UniFi Controller Section -->
                    <div class="space-y-4">
                        <h3 class="text-xs font-bold text-blue-400 uppercase tracking-widest flex items-center gap-2">
                            <i data-lucide="server" class="w-3.5 h-3.5"></i>
                            UniFi Controller
                        </h3>

                        <div>
                            <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Controller URL *</label>
                            <div class="relative">
                                <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="globe" class="w-4 h-4"></i></span>
                                <input type="url" name="controller_url" required
                                       class="setup-input"
                                       placeholder="https://192.168.1.1"
                                       value="<?= htmlspecialchars($_POST['controller_url'] ?? '') ?>">
                            </div>
                        </div>

                        <div>
                            <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">API Key *</label>
                            <div class="relative">
                                <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="key" class="w-4 h-4"></i></span>
                                <input type="text" name="api_key" required
                                       class="setup-input"
                                       placeholder="Your UniFi API key"
                                       value="<?= htmlspecialchars($_POST['api_key'] ?? '') ?>">
                            </div>
                            <p class="text-[11px] text-slate-600 mt-1 px-1">Settings &rarr; Admins & Users &rarr; API Keys</p>
                        </div>

                        <div>
                            <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Site ID</label>
                            <div class="relative">
                                <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="layout-grid" class="w-4 h-4"></i></span>
                                <input type="text" name="site"
                                       class="setup-input"
                                       placeholder="default"
                                       value="<?= htmlspecialchars($_POST['site'] ?? 'default') ?>">
                            </div>
                            <p class="text-[11px] text-slate-600 mt-1 px-1">Leave "default" for single-site setups</p>
                        </div>
                    </div>

                    <div class="border-t border-white/5"></div>

                    <!-- Admin Account Section -->
                    <div class="space-y-4">
                        <h3 class="text-xs font-bold text-emerald-400 uppercase tracking-widest flex items-center gap-2">
                            <i data-lucide="user-cog" class="w-3.5 h-3.5"></i>
                            Admin Account
                        </h3>

                        <div class="grid grid-cols-2 gap-3">
                            <div>
                                <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Username *</label>
                                <div class="relative">
                                    <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="user" class="w-4 h-4"></i></span>
                                    <input type="text" name="admin_username" required
                                           class="setup-input"
                                           placeholder="admin"
                                           value="<?= htmlspecialchars($_POST['admin_username'] ?? '') ?>">
                                </div>
                            </div>
                            <div>
                                <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Password *</label>
                                <div class="relative">
                                    <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="lock" class="w-4 h-4"></i></span>
                                    <input type="password" name="admin_password" required minlength="6"
                                           class="setup-input"
                                           placeholder="Min. 6 characters">
                                </div>
                            </div>
                        </div>

                        <div class="grid grid-cols-2 gap-3">
                            <div>
                                <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Full Name</label>
                                <div class="relative">
                                    <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="badge-check" class="w-4 h-4"></i></span>
                                    <input type="text" name="admin_full_name"
                                           class="setup-input"
                                           placeholder="John Doe"
                                           value="<?= htmlspecialchars($_POST['admin_full_name'] ?? '') ?>">
                                </div>
                            </div>
                            <div>
                                <label class="block text-xs font-bold text-slate-500 uppercase tracking-widest mb-1.5 px-1">Email</label>
                                <div class="relative">
                                    <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"><i data-lucide="mail" class="w-4 h-4"></i></span>
                                    <input type="email" name="admin_email"
                                           class="setup-input"
                                           placeholder="admin@example.com"
                                           value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="submit"
                            class="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3.5 rounded-xl transition shadow-xl shadow-blue-600/20 group flex items-center justify-center gap-2">
                        <i data-lucide="save" class="w-4 h-4"></i>
                        <span>Save & Continue</span>
                        <i data-lucide="arrow-right" class="w-4 h-4 group-hover:translate-x-1 transition"></i>
                    </button>
                </form>
            </div>
        <?php endif; ?>

        <footer class="mt-12 text-center text-slate-500 text-[11px] uppercase tracking-[0.3em] font-medium">
            <a href="https://www.lm-ads.com" target="_blank" class="hover:text-slate-300 transition">LM-Networks</a> &copy; 2025-2026
        </footer>
    </div>

    <script>lucide.createIcons();</script>
</body>
</html>
